version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./banco_api.sql:/docker-entrypoint-initdb.d/banco_api.sql
    environment:
      MYSQL_ROOT_PASSWORD: example

  api:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      DB_HOST: Server=db;Database=api_nba;user=root; pwd=example